### ISSUE TITLE
要开始干活啦！

### ISSUE THREAD

**Issue by Eliasthunderdog** [OSH-2018/X-zos#1]
我觉得不能再总是在报告上浪费时间了，我们开始关注具体的技术细节吧！
来明确一下目标（尽量做得有梯度一些，具体怎么个梯度法，我们可以找个实践讨论）

目标梯度：
1.  需要设计一个unikernel monitor，作用是提供一个specialized layer，简单来说，就是把QEMU扔进Unikernel里面！
2.  增加原有的接口，我们能够对unikernel做更多的事情（查看内存信息，打快照，停止运行，恢复等等）

暂定这两个，目前的主要问题是我们还没想好用哪个unikernel project作为我们开发的基础。而且对于每个unikernel 内部具体的组成细节我们也不是很清楚。

啥时候再开个研讨会？

**Comment by guanxiux** [comment]
喔喔, 周末要肝了啊, 早点比较好呢, 推荐周六早上. unikernel project的话好像有不少语言的版本, 我们熟悉的应该比较好吧, 那个用 C 的怎么样, 忘记名字了?

**Comment by Eliasthunderdog** [comment]
我们需要周五之前组织一次讨论，具体决定项目的雏形，时间线和确定项目的平台。
目前想的是用C语言，尽量闪开OCaml，就算需要的话我们也只是开发一下和OCaml的接口。

**Comment by shiiiivering** [comment]
![default](https://user-images.githubusercontent.com/37255282/39128578-b2e859a4-473a-11e8-8e84-e4ef9b8db1c7.png)
关于gdb的调试原理我觉得就可以看这个图了。其实从这上面看无论是本地调试还是远程调试，本质上都是ptrace函数的调用。然而我查了一些发现设置断点什么的都是汇编上的操作了。。。看了一下ptrace的官方文档也没看懂，就有些迷惑，不知道具体是需要哪方面的信息，往什么方向深入一些

**Comment by Eliasthunderdog** [comment]
嗯看这个图是GDBserver在做设置断点等等操作，QEMU是提供这个gdbserver的，我们可以放心，我们现在可以想想比如要调试了，那么我就在程序的入口处生成断点，那么现在的问题就是：
1. 从汇编语言的层面上是怎么设置断点的。我们需要在真正的unikernel应用入口处设置它。
2. 怎么找到入口？
第二个可能比较难，先看看第一个吧~~

**Comment by Lumosis** [comment]
为什么要关注在汇编语言上如何实现断点呢？还有*如何找到程序入口？*这个问题不太理解

**Comment by shiiiivering** [comment]
关于这个也了解过了，说是在设置断点后，gdb会在程序相应位置加一条系统调用指令，执行到这条指令后被调试的进程会发出相应信号，gdb捕捉到后会判断程序停止位置是否是设置过的断点，如果是则命中断点。不过这些还都是理论上的东西，不知道是否还要继续深入

**Comment by shiiiivering** [comment]
关于第二条我有个非常不成熟的想法，由于ptrace的调试是以信号为基础的，我们能不能假设在开发的时候可以在程序入口处添加相应指令使其发出信号呢：-（

**Comment by Lumosis** [comment]
我的调研里面有一个实例 里面直接使用gdb调试unikernal 设置断点功能可以正常使用啊 为什么要了解汇编层面上的

**Comment by Eliasthunderdog** [comment]
啊确实😨而且solo5的断点调试已经做的不错了，那就涉及不到汇编层面上...傻了傻了。准确来讲其实就是了解成功进行调试需要哪些调试信息。。比如符号表怎么搞啊之类的，像实验1中连上qemu之后需要load的那个文件类似的东西。。

**Comment by shiiiivering** [comment]
那么调研结果要用什么方式呈现呢

**Comment by Lumosis** [comment]
我传上了部分的调研报告（算是）

**Comment by Eliasthunderdog** [comment]
嗯嗯这就很好了，已经说清楚了GDB怎么调试的，还有一个RUMPRUN的实例。
